language: go

# go1.1 does not support -coverprofile flag. because of this, no go1.1 test at the moment
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci
